name = "miniflare-example"
type = "javascript"
routes = []
workers_dev = true
compatibility_date = "2021-10-05"

[vars]
ENVIRONMENT = "dev"
CACHE_KEY_PREFIX = "dev.data:"
KEY = "me"

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"
